cuisine_keywords = {
    "Italian": {
        "pizza": 5, "pasta": 5, "risotto": 4, "lasagna": 5, "gnocchi": 4, "bruschetta": 3, "carbonara": 4,
        "bolognese": 4, "tiramisu": 5, "spaghetti": 4, "fettuccine": 3, "penne": 3, "ravioli": 4, "caprese": 3,
        "prosciutto": 4, "parmesan": 4, "mozzarella": 4, "calzone": 3, "margherita": 4, "salami": 3,
        "pesto": 4, "olio d'oliva": 3, "vino rosso": 3, "ristorante": 4, "trattoria": 4, "ciao": 4,
        "espresso": 3, "cappuccino": 3, "affogato": 2, "cannoli": 3, "zabaglione": 2, "panettone": 3,
        "carpaccio": 2, "ossobuco": 3, "polenta": 3, "tagliatelle": 3, "gelato": 4, "vino bianco": 3,
        "limoncello": 3, "neapolitan": 3, "grappa": 2, "chianti": 3, "valpolicella": 2, "montepulciano": 2,
        "italiano": 5, "buongiorno": 4, "dolce vita": 4, "formaggio": 3, "arancini": 3, "porchetta": 3,
        "parmigiana": 3, "pecorino": 3, "panino": 2, "crostini": 2, "spaghetti carbonara": 4,
        "panna cotta": 3, "insalata": 2, "ciabatta": 3, "espresso macchiato": 2, "cucina": 3,
        "aglio e olio": 2, "forno": 2, "tagliolini": 2, "salsiccia": 2, "capellini": 2, "focaccia": 4,
        "napoli": 4, "roma": 4, "milano": 4, "tuscany": 3, "sicily": 3, "venice": 3, "italy": 5,
        "italian wine": 3, "italian cheese": 3, "italian kitchen": 4, "italian herbs": 3,
        "italian restaurant": 4, "authentic italian": 5, "italian cuisine": 5, "italian food": 5,
        "italian bakery": 3, "italian espresso": 3, "italian street food": 3, "nonna": 2, "italian nonna": 3,
        "italian deli": 3, "italian coffee": 3, "italian olive oil": 3, "vino italiano": 3,
        "la dolce vita": 4, "italian vibes": 3, "italian tradition": 3, "italian pride": 2,
        "italian flag": 2, "italian roots": 2, "italiano vero": 5, "mangiare": 2, "buon appetito": 4,
        "italian language": 2, "italian romantic": 1, "italian atmosphere": 2, "italian touch": 2
    },
    
    "Mexican": {
        "taco": 5, "burrito": 5, "quesadilla": 4, "nachos": 4, "enchilada": 4, "salsa": 3, "guacamole": 4,
        "fajita": 4, "chimichanga": 3, "chorizo": 4, "jalapeño": 4, "tostada": 3, "tamale": 4, "pozole": 4,
        "mole": 4, "flan": 2, "horchata": 3, "tequila": 5, "mezcal": 4, "tamarindo": 2, "elote": 4,
        "ceviche": 3, "cerveza": 3, "maíz": 3, "arroz rojo": 2, "taqueria": 4, "cantina": 3, "antojitos": 3,
        "sopes": 3, "pico de gallo": 3, "al pastor": 4, "habanero": 2, "nopal": 2, "queso fresco": 3,
        "cochinita pibil": 4, "barbacoa": 4, "carnitas": 4, "birria": 4, "aguas frescas": 2, "margarita": 4,
        "camote": 2, "mexico city": 5, "frijoles": 3, "mexicana": 4, "carne asada": 4, "gorditas": 3,
        "tlacoyo": 3, "pan dulce": 3, "aguachile": 3, "quesabirria": 3, "chilango": 2, "huevos rancheros": 3,
        "chipotle": 3, "adobo": 3, "chile relleno": 4, "menudo": 3, "tortilla": 5, "queso fundido": 3,
        "diablo sauce": 2, "churros": 4, "poblano": 3, "verde sauce": 2, "red enchilada": 2, "mariachi": 4,
        "cincodemayo": 4, "taco truck": 4, "comida": 3, "bistec": 2, "tortilleria": 2, "molé poblano": 4,
        "mex grill": 3, "latino food": 2, "hispanic cuisine": 3, "mex food": 5, "mexican grill": 4,
        "mexican kitchen": 4, "mexican cantina": 4, "mexican street food": 5, "mexican eatery": 4,
        "authentic mexican": 5, "mexican vibes": 4, "mexican roots": 4, "azteca": 3, "mayan food": 3,
        "street taco": 4, "spicy jalapeno": 2, "queso dip": 2, "taco bowl": 2, "sinaloa": 3, "chilaquiles": 4,
        "pozole rojo": 3, "baja fish taco": 3, "yucatan": 3, "mexican fiesta": 4, "ole": 2, "calaveras": 2,
        "viva mexico": 5, "mexican heritage": 3, "sombrero": 2, "mexican pride": 3, "mexican flag": 2,
        "cactus": 2, "day of the dead": 4, "tamal": 4, "chapulines": 2, "molcajete": 2, "pambazo": 2,
        "cenaduría": 2, "pozolería": 2
    },

    "Japanese": {
        "sushi": 5, "ramen": 5, "tempura": 4, "teriyaki": 4, "udon": 4, "sashimi": 5, "yakitori": 4,
        "miso": 3, "miso soup": 4, "tonkatsu": 4, "shoyu": 3, "onigiri": 3, "wasabi": 4, "matcha": 4,
        "dango": 3, "mochi": 4, "gyoza": 4, "daifuku": 3, "okonomiyaki": 4, "katsu": 3, "sake": 4,
        "karaage": 3, "nigiri": 3, "tamago": 2, "takoyaki": 4, "shabu shabu": 4, "chawanmushi": 3,
        "donburi": 4, "chirashi": 3, "kombu": 2, "wakame": 2, "mirin": 2, "daikon": 2, "nori": 3,
        "tsukemono": 2, "yuzu": 3, "edamame": 3, "zaru soba": 3, "oden": 3, "japanese curry": 4,
        "ebi fry": 3, "katsu curry": 4, "kaiseki": 4, "unagi": 4, "anago": 3, "ochazuke": 2, "gyudon": 3,
        "natto": 2, "nihon": 5, "nihongo": 3, "tokyo": 5, "osaka": 4, "kyoto": 4, "japan": 5,
        "kanpai": 4, "itadakimasu": 5, "gochisousama": 5, "nabe": 3, "yakisoba": 3, "zen cuisine": 3,
        "japanese grill": 3, "izakaya": 4, "don katsu": 3, "japanese noodles": 3, "green tea": 3,
        "rice bowl": 2, "japanese rice": 3, "street sushi": 3, "sushi bar": 4, "japanese bistro": 3,
        "sushi platter": 4, "japanese steak": 3, "nigiri set": 3, "yakitori skewers": 3, "japanese BBQ": 4,
        "sakura": 3, "sakura blossom": 2, "japanese izakaya": 4, "tokyo roll": 3, "sashimi deluxe": 4,
        "matcha dessert": 3, "bento box": 4, "real wasabi": 3, "japanese taste": 3, "rice vinegar": 2,
        "shiso": 2, "tamagoyaki": 3, "seaweed salad": 2, "japanese omelette": 3, "yakitori chicken": 3,
        "tsukune": 2, "karē": 2, "miso ramen": 3, "spicy tuna": 3, "dragon roll": 3, "japanese house": 3,
        "japanese kitchen": 4, "japanese tradition": 3, "nippon": 3, "fuji": 3, "bento": 3,
        "origami": 2, "samurai": 2, "tokyo vibes": 3, "harajuku": 2, "buddhist cuisine": 2,
        "kimono": 2, "nippon food": 4
    },

    "French": {
        "baguette": 5, "croissant": 5, "escargot": 4, "ratatouille": 4, "quiche": 4, "crêpe": 4,
        "soufflé": 3, "foie gras": 5, "coq au vin": 4, "bouillabaisse": 4, "cassoulet": 4,
        "tarte tatin": 4, "fromage": 4, "brie": 3, "camembert": 3, "roquefort": 3, "vin rouge": 3,
        "vin blanc": 3, "bonjour": 4, "au jus": 3, "pâté": 3, "bistro": 4, "mousse": 3,
        "pain au chocolat": 4, "macaron": 4, "crème brûlée": 5, "french toast": 3, "steak frites": 4,
        "french fries": 2, "duck confit": 4, "beef bourguignon": 5, "tournedos": 2, "chèvre": 3,
        "tartare": 3, "andouillette": 3, "croque monsieur": 4, "croque madame": 4, "roti de porc": 3,
        "soupe à l'oignon": 4, "canelé": 3, "éclair": 4, "galette": 3, "tarte flambée": 3,
        "mille-feuille": 4, "vol-au-vent": 3, "rillettes": 3, "french": 5, "paris": 5, "marseille": 4,
        "cuisine française": 5, "haute cuisine": 5, "vin": 3, "française": 4, "menu du jour": 3,
        "amuse-bouche": 4, "entrecôte": 4, "terrine": 3, "gratin dauphinois": 4, "pissaladière": 3,
        "rouget": 2, "navarin": 2, "bouchon": 3, "gastronomie": 5, "boeuf": 3, "poulet rôti": 3,
        "salade niçoise": 3, "haricots verts": 2, "cassoulet toulousain": 3, "truite meunière": 2,
        "fleur de sel": 2, "huile de truffe": 3, "truffe": 3, "champagne": 4, "sauternes": 3,
        "beurre blanc": 3, "boulangerie": 4, "pâtisserie": 4, "resto français": 4, "apéritif": 3,
        "café au lait": 3, "petit déjeuner": 3, "plat du jour": 3, "fromagerie": 3,
        "marché français": 3, "de france": 3, "bon appétit": 5, "au revoir": 3, "merci": 3,
        "vin de table": 3, "vin mousseux": 3, "lyon": 3, "bistro français": 4, "dîner français": 4,
        "french cuisine": 5, "provence": 4, "bourgogne": 4, "gascony": 3, "normandy": 3, "alsace": 3,
        "cognac": 3, "lavender fields": 2, "french market": 3, "parisian café": 4, "french vibe": 3
    },

    "Indian": {
        "curry": 5, "naan": 5, "tandoori": 5, "biryani": 5, "samosa": 4, "masala": 4, "dal": 4,
        "paneer": 4, "vindaloo": 3, "chutney": 3, "roti": 5, "korma": 4, "chapati": 4, "dosa": 4,
        "idli": 3, "halwa": 3, "ghee": 4, "murg": 3, "chole": 3, "ladoo": 3, "kheer": 3, "rajma": 3,
        "sambar": 3, "tikka": 4, "achar": 3, "puri": 4, "rasam": 3, "bhaji": 3, "bombay sandwich": 2,
        "basmati": 4, "jeera rice": 3, "butter chicken": 5, "dal makhani": 4, "palak paneer": 4,
        "chana masala": 4, "aloo gobi": 4, "veg thali": 4, "non veg thali": 3, "malai kofta": 4,
        "chaat": 4, "bhatura": 3, "pulao": 3, "kachori": 3, "poha": 3, "sabzi": 3, "rasgulla": 3,
        "barfi": 3, "malpua": 3, "shrikhanda": 2, "raita": 3, "lassi": 4, "mango lassi": 4, "chai": 4,
        "thali meal": 3, "indian buffet": 3, "murgh makhani": 4, "pani puri": 4, "sev puri": 3,
        "bhel puri": 3, "spicy indian": 4, "indian tandoori": 5, "punjabi": 4, "kolkata street food": 3,
        "indian grill": 4, "vindaloo curry": 3, "authentic indian": 5, "indian family food": 3,
        "indian street food": 4, "indian spices": 4, "indian restaurant": 5, "indian cuisine": 5,
        "indian food": 5, "desi": 4, "bharat": 4, "south indian": 4, "north indian": 4, "haldi": 2,
        "hing": 2, "methi": 2, "turmeric": 3, "cardamom": 2, "cumin": 3, "mustard seed": 2, "fenugreek": 2,
        "garam masala": 4, "corriander": 3, "ajwain": 2, "black pepper": 2, "tamarind": 2, "jaggery": 2,
        "sweets of india": 3, "spicy snacks": 3, "chaiwala": 2, "roadside stall": 2, "indian market": 3,
        "namaste": 3, "india": 5, "hindi": 3, "bollywood bites": 2, "holi snacks": 2, "diwali sweets": 3,
        "street chai": 2, "indian herbs": 2, "delhi bites": 3, "mumbai food": 4
    },

    "American": {
        "burger": 5, "cheeseburger": 4, "hot dog": 4, "fried chicken": 5, "bbq": 4, "barbecue": 4,
        "fries": 4, "steak": 4, "ribs": 4, "mac and cheese": 4, "apple pie": 5, "sloppy joe": 3,
        "cornbread": 3, "grits": 3, "meatloaf": 3, "buffalo wings": 4, "philly cheesesteak": 4,
        "donut": 3, "pancakes": 3, "biscuits": 3, "hash browns": 3, "root beer": 2, "cranberry sauce": 2,
        "coleslaw": 3, "s'mores": 3, "chili": 3, "brownie": 3, "tater tots": 3, "corn dog": 3,
        "chicken tenders": 3, "waffles": 4, "country fried steak": 3, "shrimp and grits": 3,
        "pulled pork": 4, "southern fried": 3, "chicken and waffles": 4, "brisket": 3, "beef jerky": 2,
        "biscuits and gravy": 3, "popcorn": 2, "tuna melt": 2, "funnel cake": 3, "new york strip": 3,
        "ranch dressing": 2, "american cheese": 3, "reuben": 3, "clam chowder": 3,
        "tex mex": 3, "american grill": 4, "diner": 4, "classic american": 5, "usa": 5, "american kitchen": 4,
        "american cuisine": 5, "american diner": 5, "all-american": 5, "stars and stripes": 4,
        "4th of july": 5, "barbecue ribs": 4, "drive-in": 3, "steakhouse": 4, "meat lovers": 3,
        "coca cola": 2, "cherry pie": 3, "grilled cheese": 4, "curly fries": 2, "deep dish": 3,
        "key lime pie": 3, "texas toast": 3, "comfort food": 5, "peanut butter": 2, "corn on the cob": 3,
        "sliders": 3, "milkshake": 4, "cheddar burger": 3, "milkshakes": 3, "american flag": 4,
        "american tradition": 4, "homestyle": 3, "american roast": 3, "state fair": 3, "hoagie": 2,
        "cobb salad": 2, "blue cheese": 2, "potato salad": 3, "chicken pot pie": 4, "turkey sandwich": 2,
        "stuffing": 2, "gravy boat": 2, "bacon bits": 2, "pimento cheese": 2, "midwestern": 3,
        "southern comfort": 4, "california burger": 3, "nashville hot": 3, "american bbq": 4,
        "boston cream pie": 3, "fluffernutter": 2, "thanksgiving dinner": 5, "route 66": 3,
        "tailgate food": 3, "football snacks": 3, "mom’s kitchen": 2, "uncle sam": 2, "new england chowder": 3
    },

    "Chinese": {
        "dumpling": 5, "noodle": 5, "fried rice": 5, "kung pao": 4, "sweet and sour": 4, "dim sum": 5,
        "chow mein": 4, "peking duck": 5, "lo mein": 4, "mapo tofu": 4, "bao": 4, "spring roll": 4,
        "wonton": 4, "char siu": 4, "egg roll": 3, "tea egg": 2, "hot pot": 4, "scallion pancake": 3,
        "congee": 3, "szechuan": 4, "soy sauce": 3, "rice wine": 3, "five-spice": 3, "bok choy": 3,
        "sesame ball": 3, "hoisin": 3, "tofu": 4, "soybean": 2, "chinese broccoli": 2, "prawn toast": 3,
        "crab rangoon": 3, "shrimp fried rice": 4, "kung pao chicken": 4, "general tso": 4,
        "fortune cookie": 2, "moo shu": 3, "spare ribs": 3, "sticky rice": 3, "chinese bbq": 3,
        "lotus root": 2, "egg foo young": 3, "chinese sausage": 3, "szechuan pepper": 3,
        "dumpling soup": 4, "noodle house": 4, "china": 5, "chinese": 5, "cantonese": 4,
        "mandarin": 3, "hunan": 3, "chop suey": 3, "beijing duck": 5, "zhajiangmian": 3, "tangyuan": 3,
        "red bean": 2, "black bean sauce": 3, "char kway teow": 3, "youtiao": 3, "lanzhou": 3,
        "shanghai": 4, "dian xin": 4, "yum cha": 4, "baozi": 3, "la mian": 3, "wan tan": 3,
        "yunnan": 3, "suan la": 3, "longjing": 2, "tea house": 3, "oriental": 2, "egg tart": 3,
        "soup dumpling": 4, "crystal shrimp": 3, "pork bun": 3, "siu mai": 4, "cheung fun": 3,
        "gai lan": 2, "beef ho fun": 3, "salt and pepper": 2, "pipa duck": 3, "lotus leaf rice": 3,
        "ginger scallion": 3, "white cut chicken": 3, "snow pea leaves": 2, "mandarin orange": 2,
        "tanghulu": 2, "zhongzi": 3, "lion head meatball": 3, "fish fragrant": 3, "doubanjiang": 2,
        "yu xiang": 2, "chinese chives": 2, "oriental taste": 2, "authentic chinese": 5,
        "sichuan hotpot": 4, "hong kong style": 4, "chinese buffet": 3, "red envelope": 2,
        "dragon dance": 2, "new year dumplings": 4, "jade garden": 2, "dynasty flavors": 2,
        "lunar feast": 2, "guangdong": 3, "tea ceremony": 3, "chopsticks": 3, "wok": 3
    },

    "Middle Eastern": {
        "hummus": 5, "falafel": 5, "shawarma": 5, "kebab": 5, "kofta": 4, "tabbouleh": 4, "fattoush": 4,
        "baba ganoush": 5, "labneh": 3, "tahini": 5, "pita": 4, "zaatar": 4, "sumac": 3, "manakish": 3,
        "mujadara": 3, "kibbeh": 4, "maqluba": 3, "molokhia": 3, "musakhan": 3, "warak enab": 3,
        "grape leaves": 3, "stuffed vine leaves": 3, "harira": 2, "lentil soup": 3, "shakshuka": 4,
        "baklava": 5, "knafeh": 4, "basbousa": 3, "halva": 3, "qatayef": 3, "date cake": 2, "meze": 3,
        "mezze": 3, "mutabal": 3, "freekeh": 2, "sambousek": 3, "arayes": 3, "fatteh": 3, "kabsa": 4,
        "mansaf": 4, "koshari": 3, "laban": 2, "esh baladi": 1, "ma'amoul": 2, "khubz": 3, "laban ayran": 2,
        "yogurt dip": 2, "lebanese salad": 3, "lebanese grill": 4, "syrian kitchen": 3, "iraqi food": 3,
        "persian rice": 3, "fesenjan": 3, "ghormeh sabzi": 4, "chelo kebab": 4, "khoresht": 3, "barbari": 2,
        "lavash": 2, "sabzi": 2, "koobideh": 3, "dolma": 4, "sarma": 3, "imam bayildi": 3, "adana kebab": 4,
        "lokum": 3, "turkish delight": 3, "turkish tea": 3, "turkish coffee": 3, "halal grill": 4,
        "halal kitchen": 4, "arabic cuisine": 5, "middle eastern food": 5, "middle eastern grill": 5,
        "authentic middle eastern": 5, "levantine": 4, "levant cuisine": 4, "arabian dishes": 3,
        "beirut style": 3, "damascus": 3, "jerusalem mix": 3, "jerusalem street food": 4,
        "israeli salad": 3, "israeli couscous": 2, "tehran": 2, "iranian kitchen": 3, "egyptian falafel": 3,
        "taameya": 3, "foul medames": 3, "shawarma plate": 4, "grilled halloumi": 3, "mint tea": 3,
        "arabic coffee": 3, "molokheya": 3, "sahlab": 2, "jordanian food": 2, "arabian wrap": 3,
        "khaleeji food": 2, "omani shuwa": 2, "qatar grill": 2, "kuwaiti rice": 2, "maghreb cuisine": 3,
        "algerian couscous": 3, "moroccan tagine": 4, "tagine": 4, "harissa": 3, "ras el hanout": 2,
        "argan oil": 2, "dates": 4, "fig jam": 2, "rose water": 2, "orange blossom": 2, "olive oil": 3
    },

    "Greek": {
        "gyros": 5, "souvlaki": 5, "moussaka": 5, "tzatziki": 5, "feta": 4, "dolma": 4, "spanakopita": 4,
        "baklava": 4, "halloumi": 4, "kalamata": 3, "pita": 4, "kleftiko": 3, "pastitsio": 4, "youvetsi": 3,
        "melitzanosalata": 3, "taramosalata": 3, "avgolemono": 3, "horta": 2, "gigantes": 3, "tiropita": 3,
        "keftedes": 3, "loukoumades": 3, "galaktoboureko": 3, "tsoureki": 2, "kokoretsi": 2, "koulouri": 2,
        "rebetiko": 1, "psari": 2, "greek salad": 5, "xoriatiki": 4, "greek yogurt": 5, "greek honey": 3,
        "grilled octopus": 3, "ouzo": 3, "metaxa": 2, "saganaki": 3, "ladera": 2, "evoo": 2, "skordalia": 3,
        "olive oil": 4, "oregano": 2, "boureki": 2, "pasteli": 2, "greek herbs": 2, "fava": 3, "lemon potato": 3,
        "tzitziki": 2, "agia": 1, "greek pastry": 3, "greek feast": 3, "greek wine": 3, "greek tavern": 3,
        "greek kitchen": 4, "authentic greek": 5, "greek house": 3, "greek island": 4, "mykonos": 3,
        "santorini": 3, "athens": 3, "greek market": 3, "greek vibes": 3, "opa": 3, "hellenic": 4,
        "filo pastry": 2, "manestra": 2, "makaronia": 2, "soumada": 2, "louza": 2, "easter bread": 2,
        "greek herbs": 2, "greek bistro": 3, "greek meze": 3, "grilled lamb": 4, "tzatziki sauce": 3,
        "greek music": 2, "greek dancing": 2, "cycladic": 2, "aegean": 2, "crete": 3, "lesvos": 2,
        "greek street food": 3, "greek diner": 3, "greek soul food": 2, "santorini sunset": 1, "ionian": 2,
        "sparta": 1, "olympus": 2, "zeus": 1, "athena": 1, "greek olive": 3, "vine leaves": 3,
        "greek-style": 3, "ancient greek": 2, "mezedes": 3, "plaka": 2, "naoussa": 1, "tsipouro": 2,
        "frappe": 2, "rakomelo": 2, "lamb gyro": 4, "baked feta": 3, "greek fusion": 2
    },
        
    "Spanish": {
        "paella": 5, "tapas": 5, "churros": 4, "gazpacho": 4, "tortilla española": 5, "jamón": 5,
        "sangria": 4, "croquetas": 4, "patatas bravas": 4, "pimientos de padrón": 3, "empanada": 3,
        "fabada": 3, "bacalao": 3, "turron": 2, "flan": 3, "zarzuela": 2, "cocido": 3, "calamares": 3,
        "ensalada rusa": 2, "queso manchego": 4, "albondigas": 3, "salmorejo": 3, "raciones": 2,
        "vino tinto": 3, "vino blanco": 3, "cava": 3, "horchata": 2, "pisto": 3, "arroz negro": 3,
        "spanish omelette": 4, "tinto de verano": 3, "aceitunas": 2, "pan con tomate": 3,
        "jamón ibérico": 5, "iberico": 4, "tapas bar": 4, "bocadillo": 3, "tapas plate": 3,
        "spanish cuisine": 5, "madrid": 4, "barcelona": 4, "sevilla": 4, "andalusia": 3, "spain": 5,
        "spanish": 5, "castilian": 3, "iberian": 3, "alicante": 3, "valencia": 4, "murcia": 3,
        "toledo": 3, "espana": 5, "bienvenido": 2, "cerveza": 3, "viva espana": 3, "ole": 2,
        "queso": 3, "pan": 2, "tortilla": 3, "camarones": 3, "langostinos": 3, "gambas al ajillo": 4,
        "pisto manchego": 3, "berenjena": 2, "chorizo": 4, "callos": 2, "pulpo": 3, "zarangollo": 2,
        "spanish wine": 3, "bodega": 3, "jamon serrano": 4, "ajo blanco": 3, "pa amb tomaquet": 3,
        "escalivada": 2, "sobrasada": 3, "coca mallorquina": 2, "tarta de santiago": 2,
        "leche frita": 2, "quesada": 2, "migas": 2, "porra antequerana": 2, "pinchos": 3,
        "zarzuela de mariscos": 2, "canelones": 2, "ensaimada": 3, "chistorra": 3, "spanish grill": 3,
        "authentic spanish": 5, "iberian pork": 3, "galician octopus": 3, "basque pintxos": 3,
        "spanish bistro": 3, "fiesta": 2, "feria": 2, "la tomatina": 2, "flamenco": 2,
        "la rambla": 2, "alhambra": 2
    },

    "Vietnamese": {
        "pho": 5, "banh mi": 5, "bun cha": 4, "goi cuon": 5, "ca phe sua da": 4, "bun bo hue": 4,
        "com tam": 4, "bun rieu": 3, "cha gio": 4, "nuoc mam": 5, "lemongrass": 4, "rice noodles": 4,
        "cilantro": 3, "fish sauce": 4, "thit nuong": 3, "bun thit nuong": 4, "hu tieu": 3,
        "mi quang": 3, "banh xeo": 4, "banh cuon": 3, "banh beo": 3, "banh bot loc": 3, "banh trang": 3,
        "bo kho": 3, "canh chua": 3, "banh chung": 2, "cha ca": 3, "bun dau mam tom": 3,
        "rau muong": 2, "banh it": 2, "che": 3, "xoi": 3, "ca kho to": 3, "thit kho": 3, "mam nem": 2,
        "mam tom": 2, "bun moc": 3, "oc": 2, "chao long": 2, "pho ga": 4, "pho bo": 5,
        "bun bo nam bo": 3, "banh gio": 2, "suon nuong": 2, "cha lua": 2, "chao ga": 2, "com ga": 3,
        "nuoc cham": 4, "da nang": 2, "saigon": 3, "hanoi": 3, "vietnam": 5, "vietnamese": 5,
        "vietnamese coffee": 4, "iced coffee": 3, "coriander": 3, "sate sauce": 2, "rice paper": 4,
        "green mango": 3, "fried shallots": 2, "lotus root salad": 2, "sticky rice": 3,
        "fish cake": 2, "grilled pork": 3, "egg rolls": 3, "herbs": 2, "street food": 3, "side of herbs": 2,
        "fresh roll": 4, "lemongrass pork": 3, "roasted duck": 2, "vietnamese soup": 4, "viet bistro": 3,
        "viet kitchen": 3, "authentic vietnamese": 5, "banh mi sandwich": 4, "ho chi minh": 3,
        "viet fusion": 2, "viet rice bowl": 3, "pho house": 3, "pho king": 2, "pho 24": 2,
        "pho real": 2, "viet roll": 3, "fish mint": 2, "nước chấm": 4, "bun mam": 3, "bun oc": 2,
        "egg yolk coffee": 2, "dessert soup": 2, "banh tet": 2, "black sesame": 2, "lotus tea": 2,
        "tra da": 1, "vietnamese spring roll": 5, "chili fish sauce": 3, "caramelized pork": 3,
        "pho broth": 4, "viet noodle bar": 3
    },

    "Thai": {
        "pad thai": 5, "green curry": 5, "red curry": 4, "massaman curry": 4, "panang curry": 4,
        "tom yum": 5, "tom kha": 4, "som tam": 5, "larb": 4, "mango sticky rice": 5, "thai basil": 5,
        "lemongrass": 4, "fish sauce": 4, "bird chili": 3, "galangal": 4, "kaffir lime": 3,
        "jasmine rice": 4, "sticky rice": 4, "thai iced tea": 4, "satay": 4, "moo ping": 3,
        "pad see ew": 4, "pad kee mao": 4, "kai jeow": 2, "tod mun": 2, "yam woon sen": 3,
        "nam tok": 3, "khao soi": 5, "gaeng keow wan": 3, "thai omelette": 3, "kai yang": 3,
        "gai pad med mamuang": 3, "khao pad": 4, "kanom jeen": 3, "look chin": 2, "pla rad prik": 3,
        "gaeng daeng": 3, "thai chili paste": 3, "nam prik": 3, "kapi": 2, "fermented shrimp paste": 2,
        "pickled garlic": 2, "coconut milk": 5, "roti sai mai": 2, "thai pancake": 2,
        "deep fried pork belly": 3, "thai-style salad": 3, "bangkok": 4, "chiang mai": 3,
        "thailand": 5, "thai cuisine": 5, "authentic thai": 5, "spicy thai": 4, "thai grill": 3,
        " isaan": 4, "royal thai": 3, "central thai": 2, "northeastern thai": 2, "southern thai": 2,
        "thai curry": 4, "thai herbs": 3, "nam jim": 3, "thai fried rice": 4, "green papaya": 3,
        "spicy papaya salad": 4, "eggplant stir fry": 2, "thai sausage": 3, "kai dao": 2,
        "coconut soup": 3, "grilled chicken": 3, "barbecue pork": 2, "street noodles": 3,
        "thai barbecue": 4, "gaeng som": 3, "yam pla duk fu": 2, "morning glory": 2, "nam pla": 3,
        "sticky mango": 4, "thai tea": 4, "thai market": 3, "thai taste": 3, "silom": 2,
        "floating market": 2, "khao tom": 2, "moo tod": 2, "thai stir fry": 3, "thai dessert": 3,
        "banana in coconut milk": 2, "kanom krok": 2, "toddy palm cake": 2, "luuk chup": 2,
        "thai bistro": 3, "thai noodle bar": 3, "thai cafe": 3, "thai home cooking": 3
    },

    "Korean": {
        "kimchi": 5, "bulgogi": 5, "bibimbap": 5, "japchae": 4, "tteokbokki": 5, "samgyeopsal": 4,
        "galbi": 4, "banchan": 5, "gochujang": 5, "doenjang": 4, "soju": 4, "makgeolli": 3,
        "kimchi jjigae": 4, "sundubu jjigae": 4, "gimbap": 5, "naengmyeon": 4, "haemul pajeon": 3,
        "mandu": 4, "dak galbi": 4, "yangnyeom chicken": 4, "korean bbq": 5, "gochugaru": 3,
        "ssam": 3, "ssamjang": 3, "bokkeumbap": 3, "gyeran mari": 3, "hobakjeon": 2, "kongguksu": 2,
        "kkakdugi": 2, "myeolchi bokkeum": 2, "jeon": 3, "gamjatang": 3, "tteokguk": 3, "budae jjigae": 4,
        "jumeokbap": 2, "cheonggukjang": 2, "haejangguk": 2, "korean fried chicken": 5,
        "k-drama food": 2, "gopchang": 3, "daikon": 2, "hangover soup": 2, "kimchi fried rice": 4,
        "korean hotpot": 3, "hotteok": 3, "injeolmi": 2, "bingsu": 3, "korean corn dog": 4,
        "bibim naengmyeon": 3, "perilla leaf": 2, "barley tea": 2, "kimbap": 5, "jangajji": 2,
        "korean pancake": 3, "military stew": 2, "rice cakes": 3, "pajeon": 3, "korean spicy": 4,
        "gangnam": 2, "seoul": 4, "busan": 3, "jeju": 3, "hanok": 2, "hallyu": 2, "taekwondo": 1,
        "hansik": 3, "korean dining": 3, "korean fusion": 3, "korean flavors": 3, "kimchi stew": 4,
        "spicy pork": 3, "rice bowl": 2, "gukbap": 2, "cheongju": 2, "k-cuisine": 3, "authentic korean": 5,
        "korean noodle": 3, "korean buffet": 3, "ssambap": 2, "chimaek": 3, "mulgogi": 2, "sujeonggwa": 2,
        "yakgwa": 2, "korean house": 3, "dongchimi": 2, "k-food": 3, "samgyetang": 3, "guksu": 2,
        "tteok": 3, "kim": 2, "guk": 2, "jjigae": 3, "banban chicken": 2, "yoogane": 1, "seolleongtang": 3,
        "sikhye": 2, "tteokbokki sauce": 3, "grilled mackerel": 2, "sweet potato noodle": 3,
        "anchovy broth": 2, "seaweed soup": 2, "korean spices": 3
    },

    "Caribbean": {
        "jerk chicken": 5, "oxtail": 5, "rice and peas": 5, "ackee and saltfish": 5, "callaloo": 4,
        "curry goat": 5, "plantain": 4, "roti": 4, "doubles": 4, "bake and shark": 3, "pelau": 3,
        "saltfish": 4, "pepperpot": 3, "breadfruit": 3, "fried dumplings": 4, "festival": 3,
        "cassava": 3, "sorrel": 3, "ginger beer": 3, "rum punch": 4, "rum cake": 4, "caribbean curry": 4,
        "conch fritters": 3, "brown stew chicken": 4, "escovitch fish": 4, "bammy": 3, "fish tea": 2,
        "macaroni pie": 3, "beef patty": 5, "chicken patty": 4, "caribbean spices": 3, "coconut rice": 3,
        "green seasoning": 3, "ginger": 2, "habanero": 3, "scotch bonnet": 4, "trinidad": 3,
        "jamaica": 5, "barbados": 3, "haiti": 3, "grenada": 3, "stew peas": 3, "peas and rice": 3,
        "goat stew": 3, "sweet potato pudding": 3, "johnny cake": 3, "caribbean jerk": 5,
        "jerk pork": 4, "creole sauce": 3, "calypso": 2, "reggae food": 3, "island flavor": 4,
        "jamaican kitchen": 4, "tropical flavor": 4, "island cuisine": 4, "spicy island": 3,
        "curried shrimp": 3, "souse": 2, "trini food": 3, "salted cod": 3, "green banana": 3,
        "calaloo soup": 2, "mango chutney": 2, "hot pepper sauce": 4, "jerk shack": 4,
        "caribbean beach": 2, "rum glazed": 2, "conch salad": 3, "bajan food": 2, "goat curry": 4,
        "bush tea": 2, "cassareep": 2, "mango chow": 2, "bake": 2, "barbadian": 2, "puerto rico": 2,
        "dominican stew": 2, "plantain tart": 2, "tamarind juice": 2, "trinidad roti": 3,
        "jerk rub": 3, "spice mix": 2, "sweet bread": 2, "tostones": 2, "fish escovitch": 3,
        "curried crab": 2, "soursop": 2, "mauby": 2, "caribbean grill": 4, "jerk festival": 2,
        "island jerk": 4, "bahamian seafood": 2, "port of spain": 2, "mobay": 2, "negril": 2,
        "island kitchen": 4, "authentic caribbean": 5, "jerk smoke": 3
    },

    "Indonesian": {
        "nasi goreng": 5, "mie goreng": 5, "sate": 5, "satay": 4, "rendang": 5, "bakso": 4,
        "soto ayam": 5, "soto betawi": 4, "ayam geprek": 4, "ayam penyet": 4, "ayam goreng": 3,
        "ayam bakar": 4, "tempeh": 4, "tempe": 4, "tahu": 3, "gado gado": 5, "lontong": 4,
        "ketupat": 4, "nasi padang": 5, "padang": 4, "indomie": 5, "mie ayam": 4, "mie rebus": 3,
        "mie jawa": 3, "mie bakso": 3, "tahu gejrot": 3, "tahu isi": 3, "perkedel": 3, "kerupuk": 3,
        "sambal": 5, "sambal matah": 4, "sambal terasi": 4, "sambal bajak": 3, "telur balado": 3,
        "balado": 3, "dendeng balado": 4, "rawon": 4, "opor ayam": 4, "gulai": 4, "sayur lodeh": 4,
        "sayur asem": 3, "tongseng": 3, "empal": 3, "pecel": 4, "nasi uduk": 4, "nasi liwet": 4,
        "nasi kuning": 4, "nasi campur": 4, "nasi bakar": 4, "klepon": 3, "kue lapis": 3,
        "kue cubit": 3, "dadar gulung": 3, "martabak manis": 4, "martabak telur": 4, "serabi": 3,
        "putu": 3, "risoles": 3, "pastel": 3, "lemper": 3, "es teler": 3, "es campur": 4,
        "cendol": 4, "kolak": 3, "pisang goreng": 4, "singkong goreng": 3, "getuk": 3,
        "ikan bakar": 4, "ikan asin": 3, "udang balado": 3, "tongkol": 2, "ikan cue": 2,
        "manado": 3, "minahasa": 2, "rica rica": 4, "babi guling": 3, "betutu": 3, "lawar": 3,
        "balinese": 3, "javanese": 4, "sundanese": 4, "batak": 3, "makassar": 3, "warung": 5,
        "rumah makan": 4, "kaki lima": 4, "angkringan": 4, "wedang jahe": 3, "kopi tubruk": 3,
        "es jeruk": 2, "teh botol": 2, "teh manis": 2, "jamu": 3, "bubur ayam": 4, "bubur sumsum": 3,
        "bubur ketan hitam": 3, "sate kambing": 4, "sate ayam": 5, "sate padang": 4,
        "indonesian": 5, "indonesian cuisine": 5, "indonesian food": 5, "nusantara": 4,
        "masakan indonesia": 5, "kuliner indonesia": 5, "kecap manis": 4, "rempah": 3,
        "bumbu": 3, "aroma nusantara": 3, "selamat makan": 3
    },

    "African": {
        "injera": 5, "doro wat": 4, "berbere": 5, "kitfo": 4, "shiro": 3, "niter kibbeh": 3, "teff": 4,
        "tibs": 3, "chickpea stew": 3, "misir wot": 4, "yebeg tibs": 3, "ethiopian coffee": 4,
        "moroccan tagine": 5, "couscous": 5, "harira": 4, "bastilla": 3, "ras el hanout": 4,
        "preserved lemon": 3, "zaalouk": 3, "kefta": 3, "mechoui": 3, "mint tea": 4, "jollof rice": 5,
        "suya": 5, "egusi soup": 5, "fufu": 5, "pounded yam": 4, "okro soup": 4, "pepper soup": 4,
        "akara": 4, "moimoi": 4, "nkwobi": 3, "abacha": 3, "ata din din": 3, "maggi cube": 2,
        "cassava": 3, "yassa": 4, "thieboudienne": 4, "mafe": 4, "chicken yassa": 4, "attieke": 4,
        "peanut stew": 4, "cow foot soup": 3, "grilled plantains": 3, "roasted maize": 3,
        "street food": 2, "spicy stew": 3, "african kitchen": 4, "african grill": 3,
        "authentic african": 5, "afro fusion": 2, "ghana": 4, "nigeria": 5, "ethiopia": 5,
        "morocco": 5, "senegal": 4, "ivory coast": 3, "togo": 3, "benin": 3, "lagos": 3,
        "accra": 3, "casablanca": 3, "addis ababa": 3, "spiced lamb": 3, "kushari": 2,
        "coconut rice": 3, "fish pepper soup": 3, "injera platter": 4, "kitoza": 2,
        "mandazi": 3, "boerewors": 3, "bobotie": 3, "samp and beans": 2, "umngqusho": 2,
        "south african curry": 2, "durban curry": 2, "nyama choma": 3, "ugali": 4, "matoke": 3,
        "sukuma wiki": 3, "pilau": 3, "chapati": 3, "tamarind sauce": 2, "chakalaka": 2,
        "african cuisine": 5, "village stew": 3, "chicken peri peri": 3, "peri peri": 4,
        "african flavors": 4, "braai": 2, "north african spices": 4, "sambusa": 3, "african feast": 4,
        "bush meat": 2, "groundnut soup": 4, "bean cake": 3, "traditional stew": 3, "malva pudding": 2,
        "tilapia soup": 2, "ginger juice": 2, "hibiscus drink": 2, "zobo": 2
    },

    "South American": {
        "feijoada": 5, "picanha": 5, "pão de queijo": 5, "coxinha": 5, "brigadeiro": 5,
        "moqueca": 4, "farofa": 4, "acarajé": 4, "tapioca": 4, "caipirinha": 5, "churrasco": 5,
        "chimichurri": 4, "empanadas": 5, "asado": 5, "mate": 4, "dulce de leche": 4,
        "arepas": 5, "pastel": 4, "curanto": 3, "anticuchos": 4, "ceviche": 5, "aji amarillo": 4,
        "quinoa": 3, "locro": 3, "humita": 2, "tamales": 4, "bandeja paisa": 4, "arepitas": 2,
        "salchipapas": 3, "pernil": 3, "choripan": 4, "malbec": 3, "mate tea": 3, "dulce de membrillo": 2,
        "pão francês": 2, "pastel de nata": 2, "sopa paraguaya": 3, "cassava": 4, "manioc": 3,
        "tres leches cake": 4, "empanada criolla": 3, "yuca fries": 3, "milanesa": 4,
        "tostones": 3, "pollo a la brasa": 4, "ajiaco": 4, "leche de tigre": 3, "banana frita": 3,
        "papas a la huancaína": 4, "chicha morada": 3, "pastelito": 2, "hallacas": 3,
        "dulce": 2, "sofrito": 2, "sancocho": 3, "tamale": 3, "curdled milk dessert": 2,
        "cachaca": 4, "brazil": 5, "argentina": 4, "peru": 4, "colombia": 4, "chile": 4,
        "uruguay": 3, "venezuela": 3, "bolivia": 3, "ecuador": 3, "paraguay": 3,
        "latin grill": 4, "south american": 5, "latin kitchen": 4, "cultural plate": 3,
        "plátano": 3, "pupusa": 3, "aji": 3, "latino": 3, "latin food": 5, "food truck": 2,
        "causa limeña": 3, "batata": 2, "mandioca": 2, "peruvian fusion": 3, "argentine steak": 4,
        "grilled skirt steak": 3, "picanha skewer": 4, "brazilian buffet": 3, "south american stew": 3,
        "regional fare": 3, "authentic brazilian": 5, "plato típico": 3, "empanada argentina": 3,
        "choripan sandwich": 3, "dulce bombon": 2, "milhoja": 2, "pan de bono": 2, "maicena": 1,
        "pastel de choclo": 3, "humitas dulces": 2, "chimichanga": 2, "chicha": 2
    },

    "German": {
        "bratwurst": 5, "sauerkraut": 5, "pretzel": 5, "schnitzel": 5, "currywurst": 5,
        "spätzle": 4, "brötchen": 4, "rouladen": 4, "kartoffelsalat": 4, "leberkäse": 3,
        "eintopf": 4, "apfelstrudel": 4, "black forest cake": 4, "wiener": 3, "frikadellen": 3,
        "mett": 3, "kohlroulade": 3, "hasenpfeffer": 2, "sauerbraten": 4, "königsberger klopse": 3,
        "weisswurst": 4, "brezel": 5, "obatzda": 3, "kasespatzle": 4, "flammkuchen": 3,
        "reiberdatschi": 2, "stollen": 3, "zwiebelkuchen": 3, "quarkkeulchen": 2, "labskaus": 2,
        "bienenstich": 3, "marzipan": 3, "speckpfannkuchen": 2, "kartoffelpuffer": 3, "senfeier": 2,
        "herring salad": 2, "beer": 5, "riesling": 3, "glühwein": 4, "radler": 3,
        "berliner": 3, "schwarzwälder kirsch": 3, "pumpernickel": 3, "himmel und erde": 2,
        "munich": 4, "berlin": 4, "oktoberfest": 5, "bavaria": 4, "frankfurt": 3,
        "german bakery": 4, "german sausage": 5, "german potato": 3, "german comfort food": 4,
        "goulash soup": 3, "mustard sauce": 3, "pickled herring": 2, "beer garden": 4,
        "federweisser": 2, "korn": 2, "altbier": 2, "dampfnudel": 3, "schupfnudeln": 2,
        "schweinshaxe": 4, "eisbein": 3, "kartoffelsuppe": 3, "linsen mit spätzle": 2,
        "german chocolate": 3, "streuselkuchen": 2, "baumkuchen": 2, "dominosteine": 1,
        "zimtsterne": 2, "lebkuchen": 3, "berliner luft": 1, "kartoffelknödel": 3,
        "semmelknödel": 3, "thuringian sausage": 3, "nürnberger rostbratwurst": 3,
        "frankfurter würstchen": 3, "weissbier": 3, "kölsch": 3, "düsseldorf mustard": 2,
        "haribo": 2, "german christmas market": 4, "advent calender": 2, "wurstsalat": 2,
        "german rye": 3, "butterkuchen": 2, "bienenstich cake": 2, "german pancake": 2,
        "german meatball": 3, "german pickles": 2, "german mustard": 3, "german sauerkraut": 4,
        "leberwurst": 3, "blutwurst": 2, "mettwurst": 2, "teewurst": 2, "landjäger": 2,
        "grünkohl": 3, "spundekäs": 2, "saumagen": 2, "schwarzbrot": 3, "rösti": 2,
        "kartoffelklösse": 2, "königsberger marzipan": 2, "apfelkuchen": 3, "zwetschgendatschi": 2
    }

    
    

}

    